### ISSUE TITLE
Documentation for `gammaRob` function

### ISSUE THREAD

**Issue by eweine** [valentint/robust#3]
Hello,

I'm interested in using the `gammaRob` function. However, it's difficult for me to figure out exactly what it is doing from the documentation. I see that there are two estimation methods: `"M"` and `"tdmean"`. My guess is that `"M"` refers to some sort of general M-estimator and `"tdmean"` is a trimmed mean estimator. However, is there any additional documentation as to what exactly these methods are doing and what control parameters exist? There is a function `gammaRob.control`, but it gives no documentation as to what different control parameters are available. From looking at the `gammaRob.control.q` file, I see many of the control parameters that are available, but it is not clear to me what they mean. Would you be able to point me towards documentation on these functions, or provide clarification here?

Thanks for your help!

Eric.

**Comment by valentint** [comment]
Dear Eric,

I am maintaining the package robust but most of it was written long before
my time (see, that the DESCRIPTION file says "Methods for robust
statistics, a state of the art in the early 2000s...".
It is better to contact some of the authors, but unfortunately in the
functions you are interested in no author's name is mentioned. I would
guess it is best to contact Alfio Marazzi ***@***.***).
One recent work on this topic (robust estimation of  univariate
distributions) is

Claudio Agostinelli, Alfio Marazzi & Victor J Yohai (2014) Robust
Estimators of the Generalized Log-Gamma Distribution, Technometrics, 56:1,
92-101, DOI: 10.1080/00401706.2013.818578
<https://doi.org/10.1080/00401706.2013.818578>


Hope this helps,
Best regards,

Valentin

**Comment by eweine** [comment]
Thanks! Will do.
